name: build g2i

on:
   push:
     tags:
       - g2i-*

   workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6

      - name: Build
        run: |
          CGO_ENABLED=0 go build g2i.go

      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
        with:
          tagRegex: "g2i-(.*)"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "g2i"
          body: "Release ${{ steps.tagName.outputs.tag }}"

