name: build k2i

on:
  push:
    tags:
      - k2i-*
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: k6-to-influx

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o k2i-linux-amd64 k2i.go 
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o k2i-linux-arm64 k2i.go 
          GOOS=windows GOARCH=386 go build -o k2i-windows-386.exe k2i.go
          GOOS=windows GOARCH=amd64 go build -o k2i-windows-amd64.exe k2i.go
          GOOS=darwin GOARCH=amd64 go build -o k2i-macos-amd64 k2i.go
          GOOS=darwin GOARCH=arm64 go build -o k2i-macos-arm64 k2i.go

      - uses: olegtarasov/get-tag@v2.1.3
        id: tagName

      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "k2i-*"
          body: "Release ${{ steps.tagName.outputs.tag }}"
